
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gateway.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Request Extend Info. Group<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public class GrpExtendInfo
    {

        /// <summary>
        /// Reserved for future use. Data is delimited by a F(0x1c) and is formatted as follows:&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Key=Value0x1cKey=Value0x1cKey=Value…<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("AdditionalInfo")]
        public string? AdditionalInfo { get; set; }

        /// <summary>
        /// Offline Auth Code.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// UsedOnly used for offline transactions.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("AuthCode")]
        public string? AuthCode { get; set; }

        /// <summary>
        /// Invoice Number.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("InvoiceNum")]
        public string? InvoiceNum { get; set; }

        /// <summary>
        /// Order Number.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Only used for purchase cards.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("OrderNum")]
        public string? OrderNum { get; set; }

        /// <summary>
        /// Voucher serial number.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Only used for offline EBT transactions.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("VoucherNum")]
        public string? VoucherNum { get; set; }
    }
}