
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gateway.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Response References Group.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public class GrpResponseRef
    {

        /// <summary>
        /// Auth date.
        /// </summary>
        [JsonProperty("AuthDate")]
        public string? AuthDate { get; set; }

        /// <summary>
        /// Auth time.
        /// </summary>
        [JsonProperty("AuthTime")]
        public string? AuthTime { get; set; }

        /// <summary>
        /// New recorded created.
        /// </summary>
        [JsonProperty("NewRecordCreated")]
        public GrpResponseRefNewRecordCreated? NewRecordCreated { get; set; }

        /// <summary>
        /// session id.
        /// </summary>
        [JsonProperty("SESSIONID")]
        public string? Sessionid { get; set; }

        /// <summary>
        /// Transaction Identifier.
        /// </summary>
        [JsonProperty("TransactionIdentifier")]
        public string? TransactionIdentifier { get; set; }
    }
}