
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gateway.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Request Terminal Info. Group<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public class GrpResponseTerminalInfo
    {

        /// <summary>
        /// Pin pad status.
        /// </summary>
        [JsonProperty("DeviceStatus")]
        public GrpResponseTerminalInfoDeviceStatus? DeviceStatus { get; set; }

        /// <summary>
        /// Pin pad’s serial number. The last 8 digit of full serial number.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Valid values:&lt;br&gt;<br/>
        /// Full serial number: 14281PP81035776,&lt;br&gt;<br/>
        /// Last 8 digit of serial number: 81035776<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("SN")]
        public string? Sn { get; set; }

        /// <summary>
        /// Only supported in Local and Cloud PDC.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// SignatureData HEX encoded: &lt;a href=&quot;https://gatewayapidocs.netevia.com/images/docs/PaymentDevices/Ingenico/Tetra/Signature/IngenicoThree-Byte ASCII Signature Format.pdf&quot; &gt;ASCII with 3-Byte ASCII Signature Format&lt;/a&gt;<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("SignatureData")]
        public string? SignatureData { get; set; }
    }
}