
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gateway.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Pin pad status.
    /// </summary>
    public enum GrpResponseTerminalInfoDeviceStatus
    {
        [JsonProperty("true")]
        True,
        [JsonProperty("false")]
        False,
        [JsonProperty("BUSY")]
        Busy,
    }

    public static class GrpResponseTerminalInfoDeviceStatusExtension
    {
        public static string Value(this GrpResponseTerminalInfoDeviceStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GrpResponseTerminalInfoDeviceStatus ToEnum(this string value)
        {
            foreach(var field in typeof(GrpResponseTerminalInfoDeviceStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GrpResponseTerminalInfoDeviceStatus)
                    {
                        return (GrpResponseTerminalInfoDeviceStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GrpResponseTerminalInfoDeviceStatus");
        }
    }
}