
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Netevia.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Card Brand.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public enum Brand
    {
        [JsonProperty("Visa")]
        Visa,
        [JsonProperty("MasterCard")]
        MasterCard,
        [JsonProperty("Discover")]
        Discover,
        [JsonProperty("Amex")]
        Amex,
        [JsonProperty("JCB")]
        Jcb,
        [JsonProperty("DinersClub")]
        DinersClub,
    }

    public static class BrandExtension
    {
        public static string Value(this Brand value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Brand ToEnum(this string value)
        {
            foreach(var field in typeof(Brand).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Brand)
                    {
                        return (Brand)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Brand");
        }
    }

}