
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Netevia.Models.Shared
{
    using Netevia.Models.Shared;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Request Extend Info. Group<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public class GrpExtendInfoSchemas1
    {

        /// <summary>
        /// Reserved for future use. Data is delimited by a F(0x1c) and is formatted as follows:&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Key=Value0x1cKey=Value0x1cKey=Value…<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("AdditionalInfo")]
        public string? AdditionalInfo { get; set; }

        /// <summary>
        /// Indicates whether partial authorization is allowed.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("AllowsPartialAuth")]
        public SchemasGrpExtendInfoAllowsPartialAuth? AllowsPartialAuth { get; set; }

        /// <summary>
        /// Offline Auth Code.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// UsedOnly used for offline transactions.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("AuthCode")]
        public string? AuthCode { get; set; }

        /// <summary>
        /// Indicates whether to check for duplicate transactions.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Duplicate check interval: 1 minute.&lt;br&gt;<br/>
        /// Note: you need to supply this field in all the request to enable this feature.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("CheckDuplicate")]
        public SchemasGrpExtendInfoCheckDuplicate? CheckDuplicate { get; set; }

        /// <summary>
        /// Indicates whether do force void transaction.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("CreditOnFailure")]
        public SchemasGrpExtendInfoCreditOnFailure? CreditOnFailure { get; set; }

        /// <summary>
        /// Merchant identifier Assigned by&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Netevia Payment Systems Administrator during registration<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("GMID")]
        public string Gmid { get; set; } = default!;

        /// <summary>
        /// Merchant password&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Only verified for Refund transactions.&lt;br&gt;<br/>
        /// It can be any value for other transactions.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("GMPW")]
        public string Gmpw { get; set; } = default!;

        /// <summary>
        /// Merchant&apos;s terminal identifier&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Assigned by Netevia Payment Systems Administrator during registration.&lt;br&gt;<br/>
        /// This field is Optional when doing Register.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("GTID")]
        public string Gtid { get; set; } = default!;

        /// <summary>
        /// Ignore AVS result from processor, default value is Y, if need to check AVS result please send it in request with N. the feature only works in TSYS and Elavon. Elavon if host return the code (A,B,C,E,N,R,W,Z) and doesnt&apos; ignore avs result code then Netevia will reject the verify request. TSYS if host return N and doesn&apos;t ignore avs result then Netevia will reject the Verify, Auth, Sale request.
        /// </summary>
        [JsonProperty("IgnoreAVSResult")]
        public SchemasGrpExtendInfoIgnoreAVSResult? IgnoreAVSResult { get; set; }

        /// <summary>
        /// Ignore CVV result from processor, default value is Y, if need to check CVV result please send it in request with N. the feature only works in TSYS and Elavon. Elavon, if doesn&apos;t Ignore CVV and host return N then Netevia will reject the Verify request. TSYS, if doesn&apos;t ignore cvv and host return N then Netevia will reject the Verify/Auth/Sale request.
        /// </summary>
        [JsonProperty("IgnoreCVVResult")]
        public SchemasGrpExtendInfoIgnoreCVVResult? IgnoreCVVResult { get; set; }

        /// <summary>
        /// Ignore Void result from processor. if processor return fail, then we force it to success. Default value is Y,
        /// </summary>
        [JsonProperty("IgnoreVoidResult")]
        public SchemasGrpExtendInfoIgnoreVoidResult? IgnoreVoidResult { get; set; }

        /// <summary>
        /// Invoice Number.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("InvoiceNum")]
        public string? InvoiceNum { get; set; }

        /// <summary>
        /// Indicates whether is an offline transaction.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("IsOffline")]
        public SchemasGrpExtendInfoIsOffline? IsOffline { get; set; }

        /// <summary>
        /// This field is used when sending a request to a PDC. Indicates whether the card data should be retrieved using the pinpad(&quot;Y&quot;) or it is not needed(Void/Refund) or already provided in the request(&quot;N&quot;). This works for all entry modes Manual/Swipe/EMV/Contactless.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("NeedSwipeCard")]
        public SchemasGrpExtendInfoNeedSwipeCard? NeedSwipeCard { get; set; }

        /// <summary>
        /// Order Number.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Only used for purchase cards.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("OrderNum")]
        public string? OrderNum { get; set; }

        /// <summary>
        /// Transaction Type.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("TransType")]
        public SchemasGrpExtendInfoTransType TransType { get; set; } = default!;

        /// <summary>
        /// Indicates whether verify card when doing CreateCardToken.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("VerifyCard")]
        public SchemasGrpExtendInfoVerifyCard? VerifyCard { get; set; }

        /// <summary>
        /// Voucher serial number.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Only used for offline EBT transactions.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("VoucherNum")]
        public string? VoucherNum { get; set; }
    }
}