
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Netevia.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// PIN Group.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public class GrpPIN
    {

        /// <summary>
        /// Used to create the base PIN encryption key for DUKPT PIN Debit and EBT transactions. Mandatory for PIN Debit and EBT transactions.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("KSN")]
        public string? Ksn { get; set; }

        /// <summary>
        /// Contains the Encrypted PIN Block for the Debit or EBT or EMV with PIN transaction being submitted<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("PinBlock")]
        public string? PinBlock { get; set; }
    }
}