
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Netevia.Models.Shared
{
    using Netevia.Models.Shared;
    using Netevia.Utils;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using System.Numerics;
    using System;
    

    public class ResponseGenericType
    {
        private ResponseGenericType(string value) { Value = value; }

        public string Value { get; private set; }
        public static ResponseGenericType GrpTraceSchemas { get { return new ResponseGenericType("grp_trace_Schemas"); } }
        
        public static ResponseGenericType GrpResponseAmountSchemas { get { return new ResponseGenericType("grp_responseAmount_Schemas"); } }
        
        public static ResponseGenericType GrpResponseCardInfoSchemas { get { return new ResponseGenericType("grp_responseCardInfo_Schemas"); } }
        
        public static ResponseGenericType GrpResponseEMVSchemas { get { return new ResponseGenericType("grp_responseEMV_Schemas"); } }
        
        public static ResponseGenericType GrpResponseRefSchemas { get { return new ResponseGenericType("grp_responseRef_Schemas"); } }
        
        public static ResponseGenericType GrpResponseMerchantSchemas { get { return new ResponseGenericType("grp_responseMerchant_Schemas"); } }
        
        public static ResponseGenericType Null { get { return new ResponseGenericType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(ResponseGenericType v) { return v.Value; }
        public static ResponseGenericType FromString(string v) {
            switch(v) {
                case "grp_trace_Schemas": return GrpTraceSchemas;
                case "grp_responseAmount_Schemas": return GrpResponseAmountSchemas;
                case "grp_responseCardInfo_Schemas": return GrpResponseCardInfoSchemas;
                case "grp_responseEMV_Schemas": return GrpResponseEMVSchemas;
                case "grp_responseRef_Schemas": return GrpResponseRefSchemas;
                case "grp_responseMerchant_Schemas": return GrpResponseMerchantSchemas;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for ResponseGenericType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ResponseGenericType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    
/// <summary>
/// Result Group.<br/>
/// 
/// <remarks>
/// 
/// </remarks>
/// </summary>
    [JsonConverter(typeof(ResponseGeneric.ResponseGenericConverter))]
    public class ResponseGeneric {
        public ResponseGeneric(ResponseGenericType type) {
            Type = type;
        }
        public GrpTraceSchemas? GrpTraceSchemas { get; set; } 
        public GrpResponseAmountSchemas? GrpResponseAmountSchemas { get; set; } 
        public GrpResponseCardInfoSchemas? GrpResponseCardInfoSchemas { get; set; } 
        public GrpResponseEMVSchemas? GrpResponseEMVSchemas { get; set; } 
        public GrpResponseRefSchemas? GrpResponseRefSchemas { get; set; } 
        public GrpResponseMerchantSchemas? GrpResponseMerchantSchemas { get; set; } 

        public ResponseGenericType Type { get; set; }


        public static ResponseGeneric CreateGrpTraceSchemas(GrpTraceSchemas grpTraceSchemas) {
            ResponseGenericType typ = ResponseGenericType.GrpTraceSchemas;

            ResponseGeneric res = new ResponseGeneric(typ);
            res.GrpTraceSchemas = grpTraceSchemas;
            return res;
        }

        public static ResponseGeneric CreateGrpResponseAmountSchemas(GrpResponseAmountSchemas grpResponseAmountSchemas) {
            ResponseGenericType typ = ResponseGenericType.GrpResponseAmountSchemas;

            ResponseGeneric res = new ResponseGeneric(typ);
            res.GrpResponseAmountSchemas = grpResponseAmountSchemas;
            return res;
        }

        public static ResponseGeneric CreateGrpResponseCardInfoSchemas(GrpResponseCardInfoSchemas grpResponseCardInfoSchemas) {
            ResponseGenericType typ = ResponseGenericType.GrpResponseCardInfoSchemas;

            ResponseGeneric res = new ResponseGeneric(typ);
            res.GrpResponseCardInfoSchemas = grpResponseCardInfoSchemas;
            return res;
        }

        public static ResponseGeneric CreateGrpResponseEMVSchemas(GrpResponseEMVSchemas grpResponseEMVSchemas) {
            ResponseGenericType typ = ResponseGenericType.GrpResponseEMVSchemas;

            ResponseGeneric res = new ResponseGeneric(typ);
            res.GrpResponseEMVSchemas = grpResponseEMVSchemas;
            return res;
        }

        public static ResponseGeneric CreateGrpResponseRefSchemas(GrpResponseRefSchemas grpResponseRefSchemas) {
            ResponseGenericType typ = ResponseGenericType.GrpResponseRefSchemas;

            ResponseGeneric res = new ResponseGeneric(typ);
            res.GrpResponseRefSchemas = grpResponseRefSchemas;
            return res;
        }

        public static ResponseGeneric CreateGrpResponseMerchantSchemas(GrpResponseMerchantSchemas grpResponseMerchantSchemas) {
            ResponseGenericType typ = ResponseGenericType.GrpResponseMerchantSchemas;

            ResponseGeneric res = new ResponseGeneric(typ);
            res.GrpResponseMerchantSchemas = grpResponseMerchantSchemas;
            return res;
        }

        public static ResponseGeneric CreateNull() {
            ResponseGenericType typ = ResponseGenericType.Null;
            return new ResponseGeneric(typ);
        }

        public class ResponseGenericConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(ResponseGeneric);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    GrpTraceSchemas? grpTraceSchemas = ResponseBodyDeserializer.Deserialize<GrpTraceSchemas>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new ResponseGeneric(ResponseGenericType.GrpTraceSchemas) {
                        GrpTraceSchemas = grpTraceSchemas
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpResponseAmountSchemas? grpResponseAmountSchemas = ResponseBodyDeserializer.Deserialize<GrpResponseAmountSchemas>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new ResponseGeneric(ResponseGenericType.GrpResponseAmountSchemas) {
                        GrpResponseAmountSchemas = grpResponseAmountSchemas
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpResponseRefSchemas? grpResponseRefSchemas = ResponseBodyDeserializer.Deserialize<GrpResponseRefSchemas>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new ResponseGeneric(ResponseGenericType.GrpResponseRefSchemas) {
                        GrpResponseRefSchemas = grpResponseRefSchemas
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpResponseMerchantSchemas? grpResponseMerchantSchemas = ResponseBodyDeserializer.Deserialize<GrpResponseMerchantSchemas>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new ResponseGeneric(ResponseGenericType.GrpResponseMerchantSchemas) {
                        GrpResponseMerchantSchemas = grpResponseMerchantSchemas
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpResponseEMVSchemas? grpResponseEMVSchemas = ResponseBodyDeserializer.Deserialize<GrpResponseEMVSchemas>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new ResponseGeneric(ResponseGenericType.GrpResponseEMVSchemas) {
                        GrpResponseEMVSchemas = grpResponseEMVSchemas
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpResponseCardInfoSchemas? grpResponseCardInfoSchemas = ResponseBodyDeserializer.Deserialize<GrpResponseCardInfoSchemas>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new ResponseGeneric(ResponseGenericType.GrpResponseCardInfoSchemas) {
                        GrpResponseCardInfoSchemas = grpResponseCardInfoSchemas
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                ResponseGeneric res = (ResponseGeneric)value;
                if (ResponseGenericType.FromString(res.Type).Equals(ResponseGenericType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.GrpTraceSchemas != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpTraceSchemas));
                    return;
                }
                if (res.GrpResponseAmountSchemas != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpResponseAmountSchemas));
                    return;
                }
                if (res.GrpResponseCardInfoSchemas != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpResponseCardInfoSchemas));
                    return;
                }
                if (res.GrpResponseEMVSchemas != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpResponseEMVSchemas));
                    return;
                }
                if (res.GrpResponseRefSchemas != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpResponseRefSchemas));
                    return;
                }
                if (res.GrpResponseMerchantSchemas != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpResponseMerchantSchemas));
                    return;
                }

            }
        }

    }

}