
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Netevia.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Indicates whether to check for duplicate transactions.&lt;br&gt;<br/>
    /// 
    /// <remarks>
    /// Duplicate check interval: 1 minute.&lt;br&gt;<br/>
    /// Note: you need to supply this field in all the request to enable this feature.<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum SchemasGrpCardDataEncryptionCheckDuplicate
    {
        [JsonProperty("Y")]
        Y,
        [JsonProperty("N")]
        N,
    }

    public static class SchemasGrpCardDataEncryptionCheckDuplicateExtension
    {
        public static string Value(this SchemasGrpCardDataEncryptionCheckDuplicate value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static SchemasGrpCardDataEncryptionCheckDuplicate ToEnum(this string value)
        {
            foreach(var field in typeof(SchemasGrpCardDataEncryptionCheckDuplicate).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is SchemasGrpCardDataEncryptionCheckDuplicate)
                    {
                        return (SchemasGrpCardDataEncryptionCheckDuplicate)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum SchemasGrpCardDataEncryptionCheckDuplicate");
        }
    }

}