
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Netevia.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Only supported for swipe/manual key entry transactions in Local and Cloud PDC and for electronic signature capable terminals. Indicates whether PDC returns signature data in response message.
    /// </summary>
    public enum SchemasNeedSignature
    {
        [JsonProperty("Y")]
        Y,
        [JsonProperty("N")]
        N,
    }

    public static class SchemasNeedSignatureExtension
    {
        public static string Value(this SchemasNeedSignature value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static SchemasNeedSignature ToEnum(this string value)
        {
            foreach(var field in typeof(SchemasNeedSignature).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is SchemasNeedSignature)
                    {
                        return (SchemasNeedSignature)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum SchemasNeedSignature");
        }
    }

}