
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Netevia.Models.Operations
{
    using Netevia.Models.Shared;
    using Netevia.Utils;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using System.Numerics;
    using System;
    

    public class ControlDesktopPDCRequestBodyType
    {
        private ControlDesktopPDCRequestBodyType(string value) { Value = value; }

        public string Value { get; private set; }
        public static ControlDesktopPDCRequestBodyType GrpAmount { get { return new ControlDesktopPDCRequestBodyType("grp_amount"); } }
        
        public static ControlDesktopPDCRequestBodyType GrpExtendInfo { get { return new ControlDesktopPDCRequestBodyType("grp_extendInfo"); } }
        
        public static ControlDesktopPDCRequestBodyType GrpLvl3 { get { return new ControlDesktopPDCRequestBodyType("grp_Lvl3"); } }
        
        public static ControlDesktopPDCRequestBodyType GrpTrace { get { return new ControlDesktopPDCRequestBodyType("grp_trace"); } }
        
        public static ControlDesktopPDCRequestBodyType GrpCardInfo { get { return new ControlDesktopPDCRequestBodyType("grp_cardInfo"); } }
        
        public static ControlDesktopPDCRequestBodyType GrpTerminalInfo { get { return new ControlDesktopPDCRequestBodyType("grp_terminalInfo"); } }
        
        public static ControlDesktopPDCRequestBodyType GrpEMV { get { return new ControlDesktopPDCRequestBodyType("grp_EMV"); } }
        
        public static ControlDesktopPDCRequestBodyType GrpCardDataEncryption { get { return new ControlDesktopPDCRequestBodyType("grp_cardDataEncryption"); } }
        
        public static ControlDesktopPDCRequestBodyType GrpPIN { get { return new ControlDesktopPDCRequestBodyType("grp_PIN"); } }
        
        public static ControlDesktopPDCRequestBodyType Null { get { return new ControlDesktopPDCRequestBodyType("null"); } } 

        public override string ToString() { return Value; }
        public static implicit operator String(ControlDesktopPDCRequestBodyType v) { return v.Value; }
        public static ControlDesktopPDCRequestBodyType FromString(string v) {
            switch(v) {
                case "grp_amount": return GrpAmount;
                case "grp_extendInfo": return GrpExtendInfo;
                case "grp_Lvl3": return GrpLvl3;
                case "grp_trace": return GrpTrace;
                case "grp_cardInfo": return GrpCardInfo;
                case "grp_terminalInfo": return GrpTerminalInfo;
                case "grp_EMV": return GrpEMV;
                case "grp_cardDataEncryption": return GrpCardDataEncryption;
                case "grp_PIN": return GrpPIN;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for ControlDesktopPDCRequestBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ControlDesktopPDCRequestBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    
/// <summary>
/// Generic Request body
/// </summary>
    [JsonConverter(typeof(ControlDesktopPDCRequestBody.ControlDesktopPDCRequestBodyConverter))]
    public class ControlDesktopPDCRequestBody {
        public ControlDesktopPDCRequestBody(ControlDesktopPDCRequestBodyType type) {
            Type = type;
        }
        public GrpAmount? GrpAmount { get; set; } 
        public GrpExtendInfo? GrpExtendInfo { get; set; } 
        public GrpLvl3? GrpLvl3 { get; set; } 
        public GrpTrace? GrpTrace { get; set; } 
        public GrpCardInfo? GrpCardInfo { get; set; } 
        public GrpTerminalInfo? GrpTerminalInfo { get; set; } 
        public GrpEMV? GrpEMV { get; set; } 
        public GrpCardDataEncryption? GrpCardDataEncryption { get; set; } 
        public GrpPIN? GrpPIN { get; set; } 

        public ControlDesktopPDCRequestBodyType Type {get; set; }


        public static ControlDesktopPDCRequestBody CreateGrpAmount(GrpAmount grpAmount) {
            ControlDesktopPDCRequestBodyType typ = ControlDesktopPDCRequestBodyType.GrpAmount;

            ControlDesktopPDCRequestBody res = new ControlDesktopPDCRequestBody(typ);
            res.GrpAmount = grpAmount;
            return res;
        }

        public static ControlDesktopPDCRequestBody CreateGrpExtendInfo(GrpExtendInfo grpExtendInfo) {
            ControlDesktopPDCRequestBodyType typ = ControlDesktopPDCRequestBodyType.GrpExtendInfo;

            ControlDesktopPDCRequestBody res = new ControlDesktopPDCRequestBody(typ);
            res.GrpExtendInfo = grpExtendInfo;
            return res;
        }

        public static ControlDesktopPDCRequestBody CreateGrpLvl3(GrpLvl3 grpLvl3) {
            ControlDesktopPDCRequestBodyType typ = ControlDesktopPDCRequestBodyType.GrpLvl3;

            ControlDesktopPDCRequestBody res = new ControlDesktopPDCRequestBody(typ);
            res.GrpLvl3 = grpLvl3;
            return res;
        }

        public static ControlDesktopPDCRequestBody CreateGrpTrace(GrpTrace grpTrace) {
            ControlDesktopPDCRequestBodyType typ = ControlDesktopPDCRequestBodyType.GrpTrace;

            ControlDesktopPDCRequestBody res = new ControlDesktopPDCRequestBody(typ);
            res.GrpTrace = grpTrace;
            return res;
        }

        public static ControlDesktopPDCRequestBody CreateGrpCardInfo(GrpCardInfo grpCardInfo) {
            ControlDesktopPDCRequestBodyType typ = ControlDesktopPDCRequestBodyType.GrpCardInfo;

            ControlDesktopPDCRequestBody res = new ControlDesktopPDCRequestBody(typ);
            res.GrpCardInfo = grpCardInfo;
            return res;
        }

        public static ControlDesktopPDCRequestBody CreateGrpTerminalInfo(GrpTerminalInfo grpTerminalInfo) {
            ControlDesktopPDCRequestBodyType typ = ControlDesktopPDCRequestBodyType.GrpTerminalInfo;

            ControlDesktopPDCRequestBody res = new ControlDesktopPDCRequestBody(typ);
            res.GrpTerminalInfo = grpTerminalInfo;
            return res;
        }

        public static ControlDesktopPDCRequestBody CreateGrpEMV(GrpEMV grpEMV) {
            ControlDesktopPDCRequestBodyType typ = ControlDesktopPDCRequestBodyType.GrpEMV;

            ControlDesktopPDCRequestBody res = new ControlDesktopPDCRequestBody(typ);
            res.GrpEMV = grpEMV;
            return res;
        }

        public static ControlDesktopPDCRequestBody CreateGrpCardDataEncryption(GrpCardDataEncryption grpCardDataEncryption) {
            ControlDesktopPDCRequestBodyType typ = ControlDesktopPDCRequestBodyType.GrpCardDataEncryption;

            ControlDesktopPDCRequestBody res = new ControlDesktopPDCRequestBody(typ);
            res.GrpCardDataEncryption = grpCardDataEncryption;
            return res;
        }

        public static ControlDesktopPDCRequestBody CreateGrpPIN(GrpPIN grpPIN) {
            ControlDesktopPDCRequestBodyType typ = ControlDesktopPDCRequestBodyType.GrpPIN;

            ControlDesktopPDCRequestBody res = new ControlDesktopPDCRequestBody(typ);
            res.GrpPIN = grpPIN;
            return res;
        }

        public static ControlDesktopPDCRequestBody CreateNull() {
            ControlDesktopPDCRequestBodyType typ = ControlDesktopPDCRequestBodyType.Null;
            return new ControlDesktopPDCRequestBody(typ);
        }

        public class ControlDesktopPDCRequestBodyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(ControlDesktopPDCRequestBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    GrpPIN? grpPIN = JsonConvert.DeserializeObject<GrpPIN>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(GrpPIN), "string")});
                    return new ControlDesktopPDCRequestBody(ControlDesktopPDCRequestBodyType.GrpPIN) {
                        GrpPIN = grpPIN
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpTrace? grpTrace = JsonConvert.DeserializeObject<GrpTrace>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(GrpTrace), "string")});
                    return new ControlDesktopPDCRequestBody(ControlDesktopPDCRequestBodyType.GrpTrace) {
                        GrpTrace = grpTrace
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpCardDataEncryption? grpCardDataEncryption = JsonConvert.DeserializeObject<GrpCardDataEncryption>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(GrpCardDataEncryption), "string")});
                    return new ControlDesktopPDCRequestBody(ControlDesktopPDCRequestBodyType.GrpCardDataEncryption) {
                        GrpCardDataEncryption = grpCardDataEncryption
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpAmount? grpAmount = JsonConvert.DeserializeObject<GrpAmount>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(GrpAmount), "string")});
                    return new ControlDesktopPDCRequestBody(ControlDesktopPDCRequestBodyType.GrpAmount) {
                        GrpAmount = grpAmount
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpExtendInfo? grpExtendInfo = JsonConvert.DeserializeObject<GrpExtendInfo>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(GrpExtendInfo), "string")});
                    return new ControlDesktopPDCRequestBody(ControlDesktopPDCRequestBodyType.GrpExtendInfo) {
                        GrpExtendInfo = grpExtendInfo
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpTerminalInfo? grpTerminalInfo = JsonConvert.DeserializeObject<GrpTerminalInfo>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(GrpTerminalInfo), "string")});
                    return new ControlDesktopPDCRequestBody(ControlDesktopPDCRequestBodyType.GrpTerminalInfo) {
                        GrpTerminalInfo = grpTerminalInfo
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpLvl3? grpLvl3 = JsonConvert.DeserializeObject<GrpLvl3>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(GrpLvl3), "string")});
                    return new ControlDesktopPDCRequestBody(ControlDesktopPDCRequestBodyType.GrpLvl3) {
                        GrpLvl3 = grpLvl3
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpCardInfo? grpCardInfo = JsonConvert.DeserializeObject<GrpCardInfo>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(GrpCardInfo), "string")});
                    return new ControlDesktopPDCRequestBody(ControlDesktopPDCRequestBodyType.GrpCardInfo) {
                        GrpCardInfo = grpCardInfo
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpEMV? grpEMV = JsonConvert.DeserializeObject<GrpEMV>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(GrpEMV), "string")});
                    return new ControlDesktopPDCRequestBody(ControlDesktopPDCRequestBodyType.GrpEMV) {
                        GrpEMV = grpEMV
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                ControlDesktopPDCRequestBody res = (ControlDesktopPDCRequestBody)value;
                if (ControlDesktopPDCRequestBodyType.FromString(res.Type).Equals(ControlDesktopPDCRequestBodyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.GrpAmount != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpAmount));
                    return;
                }
                if (res.GrpExtendInfo != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpExtendInfo));
                    return;
                }
                if (res.GrpLvl3 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpLvl3));
                    return;
                }
                if (res.GrpTrace != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpTrace));
                    return;
                }
                if (res.GrpCardInfo != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpCardInfo));
                    return;
                }
                if (res.GrpTerminalInfo != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpTerminalInfo));
                    return;
                }
                if (res.GrpEMV != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpEMV));
                    return;
                }
                if (res.GrpCardDataEncryption != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpCardDataEncryption));
                    return;
                }
                if (res.GrpPIN != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpPIN));
                    return;
                }

            }
        }

    }


}