
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Netevia.Models.Operations
{
    using Netevia.Models.Shared;
    using Netevia.Utils;
    
    public class RestAPIv2BatchRequest
    {

        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=GMID")]
        public string Gmid { get; set; } = default!;

        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=NeedSwipeCard")]
        public NeedSwipeCard? NeedSwipeCard { get; set; }

        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=TerminalType")]
        public TerminalType? TerminalType { get; set; }

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=TransType")]
        public TransType TransType { get; set; } = default!;

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public RequestGeneric RequestGeneric { get; set; } = default!;
    }
}