
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Netevia.Models.Operations
{
    using Netevia.Models.Shared;
    using Netevia.Utils;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using System.Numerics;
    using System;
    

    public class RestAPIv2RequestBodyType
    {
        private RestAPIv2RequestBodyType(string value) { Value = value; }

        public string Value { get; private set; }
        public static RestAPIv2RequestBodyType GrpAmount { get { return new RestAPIv2RequestBodyType("grp_amount"); } }
        
        public static RestAPIv2RequestBodyType GrpExtendInfo { get { return new RestAPIv2RequestBodyType("grp_extendInfo"); } }
        
        public static RestAPIv2RequestBodyType GrpLvl3 { get { return new RestAPIv2RequestBodyType("grp_Lvl3"); } }
        
        public static RestAPIv2RequestBodyType GrpTrace { get { return new RestAPIv2RequestBodyType("grp_trace"); } }
        
        public static RestAPIv2RequestBodyType GrpCardInfo { get { return new RestAPIv2RequestBodyType("grp_cardInfo"); } }
        
        public static RestAPIv2RequestBodyType GrpTerminalInfo { get { return new RestAPIv2RequestBodyType("grp_terminalInfo"); } }
        
        public static RestAPIv2RequestBodyType GrpEMV { get { return new RestAPIv2RequestBodyType("grp_EMV"); } }
        
        public static RestAPIv2RequestBodyType GrpCardDataEncryption { get { return new RestAPIv2RequestBodyType("grp_cardDataEncryption"); } }
        
        public static RestAPIv2RequestBodyType GrpPIN { get { return new RestAPIv2RequestBodyType("grp_PIN"); } }
        
        public static RestAPIv2RequestBodyType Null { get { return new RestAPIv2RequestBodyType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(RestAPIv2RequestBodyType v) { return v.Value; }
        public static RestAPIv2RequestBodyType FromString(string v) {
            switch(v) {
                case "grp_amount": return GrpAmount;
                case "grp_extendInfo": return GrpExtendInfo;
                case "grp_Lvl3": return GrpLvl3;
                case "grp_trace": return GrpTrace;
                case "grp_cardInfo": return GrpCardInfo;
                case "grp_terminalInfo": return GrpTerminalInfo;
                case "grp_EMV": return GrpEMV;
                case "grp_cardDataEncryption": return GrpCardDataEncryption;
                case "grp_PIN": return GrpPIN;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for RestAPIv2RequestBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((RestAPIv2RequestBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    
/// <summary>
/// Generic Request body
/// </summary>
    [JsonConverter(typeof(RestAPIv2RequestBody.RestAPIv2RequestBodyConverter))]
    public class RestAPIv2RequestBody {
        public RestAPIv2RequestBody(RestAPIv2RequestBodyType type) {
            Type = type;
        }
        public GrpAmount? GrpAmount { get; set; } 
        public GrpExtendInfo? GrpExtendInfo { get; set; } 
        public GrpLvl3? GrpLvl3 { get; set; } 
        public GrpTrace? GrpTrace { get; set; } 
        public GrpCardInfo? GrpCardInfo { get; set; } 
        public GrpTerminalInfo? GrpTerminalInfo { get; set; } 
        public GrpEMV? GrpEMV { get; set; } 
        public GrpCardDataEncryption? GrpCardDataEncryption { get; set; } 
        public GrpPIN? GrpPIN { get; set; } 

        public RestAPIv2RequestBodyType Type { get; set; }


        public static RestAPIv2RequestBody CreateGrpAmount(GrpAmount grpAmount) {
            RestAPIv2RequestBodyType typ = RestAPIv2RequestBodyType.GrpAmount;

            RestAPIv2RequestBody res = new RestAPIv2RequestBody(typ);
            res.GrpAmount = grpAmount;
            return res;
        }

        public static RestAPIv2RequestBody CreateGrpExtendInfo(GrpExtendInfo grpExtendInfo) {
            RestAPIv2RequestBodyType typ = RestAPIv2RequestBodyType.GrpExtendInfo;

            RestAPIv2RequestBody res = new RestAPIv2RequestBody(typ);
            res.GrpExtendInfo = grpExtendInfo;
            return res;
        }

        public static RestAPIv2RequestBody CreateGrpLvl3(GrpLvl3 grpLvl3) {
            RestAPIv2RequestBodyType typ = RestAPIv2RequestBodyType.GrpLvl3;

            RestAPIv2RequestBody res = new RestAPIv2RequestBody(typ);
            res.GrpLvl3 = grpLvl3;
            return res;
        }

        public static RestAPIv2RequestBody CreateGrpTrace(GrpTrace grpTrace) {
            RestAPIv2RequestBodyType typ = RestAPIv2RequestBodyType.GrpTrace;

            RestAPIv2RequestBody res = new RestAPIv2RequestBody(typ);
            res.GrpTrace = grpTrace;
            return res;
        }

        public static RestAPIv2RequestBody CreateGrpCardInfo(GrpCardInfo grpCardInfo) {
            RestAPIv2RequestBodyType typ = RestAPIv2RequestBodyType.GrpCardInfo;

            RestAPIv2RequestBody res = new RestAPIv2RequestBody(typ);
            res.GrpCardInfo = grpCardInfo;
            return res;
        }

        public static RestAPIv2RequestBody CreateGrpTerminalInfo(GrpTerminalInfo grpTerminalInfo) {
            RestAPIv2RequestBodyType typ = RestAPIv2RequestBodyType.GrpTerminalInfo;

            RestAPIv2RequestBody res = new RestAPIv2RequestBody(typ);
            res.GrpTerminalInfo = grpTerminalInfo;
            return res;
        }

        public static RestAPIv2RequestBody CreateGrpEMV(GrpEMV grpEMV) {
            RestAPIv2RequestBodyType typ = RestAPIv2RequestBodyType.GrpEMV;

            RestAPIv2RequestBody res = new RestAPIv2RequestBody(typ);
            res.GrpEMV = grpEMV;
            return res;
        }

        public static RestAPIv2RequestBody CreateGrpCardDataEncryption(GrpCardDataEncryption grpCardDataEncryption) {
            RestAPIv2RequestBodyType typ = RestAPIv2RequestBodyType.GrpCardDataEncryption;

            RestAPIv2RequestBody res = new RestAPIv2RequestBody(typ);
            res.GrpCardDataEncryption = grpCardDataEncryption;
            return res;
        }

        public static RestAPIv2RequestBody CreateGrpPIN(GrpPIN grpPIN) {
            RestAPIv2RequestBodyType typ = RestAPIv2RequestBodyType.GrpPIN;

            RestAPIv2RequestBody res = new RestAPIv2RequestBody(typ);
            res.GrpPIN = grpPIN;
            return res;
        }

        public static RestAPIv2RequestBody CreateNull() {
            RestAPIv2RequestBodyType typ = RestAPIv2RequestBodyType.Null;
            return new RestAPIv2RequestBody(typ);
        }

        public class RestAPIv2RequestBodyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(RestAPIv2RequestBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    GrpPIN? grpPIN = ResponseBodyDeserializer.Deserialize<GrpPIN>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RestAPIv2RequestBody(RestAPIv2RequestBodyType.GrpPIN) {
                        GrpPIN = grpPIN
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpTrace? grpTrace = ResponseBodyDeserializer.Deserialize<GrpTrace>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RestAPIv2RequestBody(RestAPIv2RequestBodyType.GrpTrace) {
                        GrpTrace = grpTrace
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpCardDataEncryption? grpCardDataEncryption = ResponseBodyDeserializer.Deserialize<GrpCardDataEncryption>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RestAPIv2RequestBody(RestAPIv2RequestBodyType.GrpCardDataEncryption) {
                        GrpCardDataEncryption = grpCardDataEncryption
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpAmount? grpAmount = ResponseBodyDeserializer.Deserialize<GrpAmount>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RestAPIv2RequestBody(RestAPIv2RequestBodyType.GrpAmount) {
                        GrpAmount = grpAmount
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpExtendInfo? grpExtendInfo = ResponseBodyDeserializer.Deserialize<GrpExtendInfo>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RestAPIv2RequestBody(RestAPIv2RequestBodyType.GrpExtendInfo) {
                        GrpExtendInfo = grpExtendInfo
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpTerminalInfo? grpTerminalInfo = ResponseBodyDeserializer.Deserialize<GrpTerminalInfo>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RestAPIv2RequestBody(RestAPIv2RequestBodyType.GrpTerminalInfo) {
                        GrpTerminalInfo = grpTerminalInfo
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpLvl3? grpLvl3 = ResponseBodyDeserializer.Deserialize<GrpLvl3>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RestAPIv2RequestBody(RestAPIv2RequestBodyType.GrpLvl3) {
                        GrpLvl3 = grpLvl3
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpCardInfo? grpCardInfo = ResponseBodyDeserializer.Deserialize<GrpCardInfo>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RestAPIv2RequestBody(RestAPIv2RequestBodyType.GrpCardInfo) {
                        GrpCardInfo = grpCardInfo
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    GrpEMV? grpEMV = ResponseBodyDeserializer.Deserialize<GrpEMV>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RestAPIv2RequestBody(RestAPIv2RequestBodyType.GrpEMV) {
                        GrpEMV = grpEMV
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                RestAPIv2RequestBody res = (RestAPIv2RequestBody)value;
                if (RestAPIv2RequestBodyType.FromString(res.Type).Equals(RestAPIv2RequestBodyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.GrpAmount != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpAmount));
                    return;
                }
                if (res.GrpExtendInfo != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpExtendInfo));
                    return;
                }
                if (res.GrpLvl3 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpLvl3));
                    return;
                }
                if (res.GrpTrace != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpTrace));
                    return;
                }
                if (res.GrpCardInfo != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpCardInfo));
                    return;
                }
                if (res.GrpTerminalInfo != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpTerminalInfo));
                    return;
                }
                if (res.GrpEMV != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpEMV));
                    return;
                }
                if (res.GrpCardDataEncryption != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpCardDataEncryption));
                    return;
                }
                if (res.GrpPIN != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GrpPIN));
                    return;
                }

            }
        }

    }

}