
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasybar.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// NOTE: This subgroup is only used for ACH transactions.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public class GrpACH
    {

        /// <summary>
        /// ACH Account type.
        /// </summary>
        [JsonProperty("AccountType")]
        public GrpACHAccountType? AccountType { get; set; }

        /// <summary>
        /// ACH account number.
        /// </summary>
        [JsonProperty("EleCheckAccountNumber")]
        public string? EleCheckAccountNumber { get; set; }

        /// <summary>
        /// ACH routing number.
        /// </summary>
        [JsonProperty("EleCheckRoutingNumber")]
        public string? EleCheckRoutingNumber { get; set; }

        /// <summary>
        /// ACH Debit transaction type.
        /// </summary>
        [JsonProperty("EleCheckServiceProvider")]
        public GrpACHEleCheckServiceProvider? EleCheckServiceProvider { get; set; }

        /// <summary>
        /// ACH Debit transaction type.
        /// </summary>
        [JsonProperty("EleCheckTransactionType")]
        public GrpACHEleCheckTransactionType? EleCheckTransactionType { get; set; }

        /// <summary>
        /// Total Credit amount for the current ACH batch.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Only used for ACH credit accounts during batching. This will be the total PayOut value and will be used to validate the credits previously stored; if the value will not match then the batch will fail.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("TotalCreditAmt")]
        public string? TotalCreditAmt { get; set; }
    }
}