
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasybar.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Additional Information about TaxAmt.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public enum GrpAmountTaxIndicator
    {
        [JsonProperty("Ntprvd")]
        Ntprvd,
        [JsonProperty("NonTax")]
        NonTax,
        [JsonProperty("Prvded")]
        Prvded,
    }

    public static class GrpAmountTaxIndicatorExtension
    {
        public static string Value(this GrpAmountTaxIndicator value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GrpAmountTaxIndicator ToEnum(this string value)
        {
            foreach(var field in typeof(GrpAmountTaxIndicator).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GrpAmountTaxIndicator)
                    {
                        return (GrpAmountTaxIndicator)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GrpAmountTaxIndicator");
        }
    }
}