
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasybar.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Card Type. Must be present when card info is from POS.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public enum GrpCardInfoMedium
    {
        [JsonProperty("Credit")]
        Credit,
        [JsonProperty("Debit")]
        Debit,
        [JsonProperty("EBTFood")]
        EBTFood,
        [JsonProperty("EBTCash")]
        EBTCash,
        [JsonProperty("Prepaid")]
        Prepaid,
        [JsonProperty("Gift")]
        Gift,
        [JsonProperty("ElectronickCheck")]
        ElectronickCheck,
    }

    public static class GrpCardInfoMediumExtension
    {
        public static string Value(this GrpCardInfoMedium value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GrpCardInfoMedium ToEnum(this string value)
        {
            foreach(var field in typeof(GrpCardInfoMedium).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GrpCardInfoMedium)
                    {
                        return (GrpCardInfoMedium)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GrpCardInfoMedium");
        }
    }
}