
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasybar.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Encryption Data Group.&lt;br&gt;<br/>
    /// 
    /// <remarks>
    /// These are present for P2PE enabled card readers<br/>
    /// 
    /// </remarks>
    /// </summary>
    public class GrpCardDataEncryption
    {

        /// <summary>
        /// Contains the track data or card number provided in an encrypted block. Be Present when card data is encrypted.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("EncrptBlock")]
        public string? EncrptBlock { get; set; }

        /// <summary>
        /// Indicates the type of data that is being encrypted.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("EncrptTrgt")]
        public GrpCardDataEncryptionEncrptTrgt? EncrptTrgt { get; set; }

        /// <summary>
        /// This is an identifier used to retrieve the private key, which is required for decryption.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("KeyID")]
        public string? KeyID { get; set; }
    }
}