
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasybar.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Response EMV Info.&lt;br&gt;<br/>
    /// 
    /// <remarks>
    /// Please Note that not all cards return these information, depending on the card, we may only return some of them.<br/>
    /// 
    /// </remarks>
    /// </summary>
    public class GrpResponseEMV
    {

        /// <summary>
        /// Application Identifier
        /// </summary>
        [JsonProperty("AID")]
        public string? Aid { get; set; }

        /// <summary>
        /// Authorization Request Cryptogram
        /// </summary>
        [JsonProperty("ARQC")]
        public string? Arqc { get; set; }

        /// <summary>
        /// Application Transaction Counter
        /// </summary>
        [JsonProperty("ATC")]
        public string? Atc { get; set; }

        /// <summary>
        /// Application Label
        /// </summary>
        [JsonProperty("ApplicationLabel")]
        public string? ApplicationLabel { get; set; }

        /// <summary>
        /// Issuer Script Template 2
        /// </summary>
        [JsonProperty("EMV72")]
        public string? Emv72 { get; set; }

        /// <summary>
        /// Authorisation Response Code
        /// </summary>
        [JsonProperty("EMV8A")]
        public string? Emv8A { get; set; }

        /// <summary>
        /// Issuer Authentication Data
        /// </summary>
        [JsonProperty("EMV91")]
        public string? Emv91 { get; set; }

        /// <summary>
        /// Transaction Status Information
        /// </summary>
        [JsonProperty("TSI")]
        public string? Tsi { get; set; }
    }
}