
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasybar.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Response Card Info Group.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public class GrpResponseCardInfo
    {

        /// <summary>
        /// Masked Card number(first six and last 4 digits).&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Maximum length = 22<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("AccountNum")]
        public string? AccountNum { get; set; }

        /// <summary>
        /// Card Brand.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("Brand")]
        public GrpResponseCardInfoBrand? Brand { get; set; }

        /// <summary>
        /// Card token.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// Set RequestCardToken to &apos;Y&apos; in the request for the server to return it.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("CardToken")]
        public string? CardToken { get; set; }

        /// <summary>
        /// Card expiration Date MMYY.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("ExpDate")]
        public string? ExpDate { get; set; }

        /// <summary>
        /// Cardholder&apos;s name from an EMV Card or from the Track1 of the magnetic stripe(for swipe with Track1).
        /// </summary>
        [JsonProperty("HolderName")]
        public string? HolderName { get; set; }

        /// <summary>
        /// Card Type.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("Medium")]
        public GrpResponseCardInfoMedium? Medium { get; set; }

        /// <summary>
        /// Only returned for &quot;CardRead&quot; requests using Gift cards. Full magnetic Track I data read from a Gift Card using a card reader.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("Track1")]
        public string? Track1 { get; set; }

        /// <summary>
        /// Only returned for &quot;CardRead&quot; requests using Gift cards. Full magnetic Track II data read from a Gift Card using a card reader.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("Track2")]
        public string? Track2 { get; set; }

        /// <summary>
        /// Only returned for &quot;CardRead&quot; requests using Gift cards. Full magnetic Track III data read from a Gift Card using a card reader.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("Track3")]
        public string? Track3 { get; set; }
    }
}