
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasybar.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The pinpad model.
    /// </summary>
    public enum GrpTerminalInfoModel
    {
        [JsonProperty("L3000")]
        L3000,
        [JsonProperty("L5000")]
        L5000,
        [JsonProperty("L7000")]
        L7000,
        [JsonProperty("L8000")]
        L8000,
        [JsonProperty("M5000")]
        M5000,
    }

    public static class GrpTerminalInfoModelExtension
    {
        public static string Value(this GrpTerminalInfoModel value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GrpTerminalInfoModel ToEnum(this string value)
        {
            foreach(var field in typeof(GrpTerminalInfoModel).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GrpTerminalInfoModel)
                    {
                        return (GrpTerminalInfoModel)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GrpTerminalInfoModel");
        }
    }
}